print("name: vyankatesh vivekanand jawrae")
print("age: 24")
print("hight: 5.1")
print("wight :57KG")
print("college name : sandip university, nashik ")
print("my dream : AI Specilisetion")
print("dream salary : 1 crore")
print("mu hobby : coding")
print("currrent year : 2026")
print("target year : 12 / 2026")