print("name: vyankatesh jaware")
print("age : 24")
print("Gender: male")
print("hight: 5.7")
print("weight: 57gm")
print("target : AI enginnr 2026")
print("my hobby: coding")
print("my dream AI arcitecture ")
print("iAm become a AISpecelist")
print("i Am pythion developer")
print("i am a AI engineer")